CREATE TABLE IF NOT EXISTS "plc-msg-history"
("id" SERIAL PRIMARY KEY,
"req" VARCHAR(2048) NOT NULL,
"resp" VARCHAR(2048) NOT NULL,
"created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"user-id" bigint NOT NULL);
